exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock
  - vendor/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-toc

name: huzecong_blog

# permalink: pretty
# future: true

title: Zecong Hu's blog
author: Zecong Hu
email: huzecong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Zecong Hu. Contains diaries, tech articles, and gibberish.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huzecong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: huzecong
disqus_shortname: huzecong-blog
# theme: jekyll-theme-kagami

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

permalink: /:year/:month/:day/:title/

collection:
  private:
    permalink: /:collection/:title/

# Pagination Settings
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num.html'
  title: ':title'
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
  # indexpage: 'index'

google_analytics: UA-48327586-2
tooltip: true

toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
timezone: UTC
