exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock
  - vendor/

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

name: huzecong_blog

permalink: pretty

title: Hu Zecong's blog
author: Hu Zecong
email: huzecong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Hu Zecong. Contains diaries, tech articles, and gibberish.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huzecong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: huzecong
disqus_shortname: huzecong-blog
# theme: jekyll-theme-kagami

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

#permalink: /:year/:month/:day/:title/

# Explicitly turn off the old code
paginate: nil
paginate_path: nil
# Pagination Settings
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num'
  title: ':title'
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
  # indexpage: 'index'

google_analytics: UA-48327586-2
